version: 2.1

executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:3.2  # Use an appropriate Ruby version
    working_directory: ~/project

jobs:
  run-ruby-script:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            bundle install
      - run:
          name: Execute Ruby File
          command: ruby your_script.rb

workflows:
  version: 2
  ruby_execution_workflow:
    jobs:
      - run-ruby-script
