version: 2.1

executors:
  jruby-executor:
    docker:
      - image: cimg/ruby:3.3.6  # Replace with the latest JRuby image
    working_directory: ~/project

jobs:
  run-jruby-script:
    executor: jruby-executor
    steps:
      - checkout
      - run:
          name: Install Bundler and Dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: Execute JRuby Script
          command: jruby your_script.rb

workflows:
  version: 2
  jruby_execution_workflow:
    jobs:
      - run-jruby-script
